import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      backgroundColor: {
        normal: '#999',
        fighting: '#ffa202',
        flying: '#96c9ff',
        poison: '#984ecf',
        ground: '#ab793b',
        rock: '#bcb889',
        bug: '#9fa525',
        ghost: '#6e4570',
        steel: '#6baed3',
        fire: '#fe612d',
        water: '#2a91ff',
        grass: '#42bf25',
        electric: '#ffdb00',
        psychic: '#ff6380',
        ice: '#43d8ff',
        dragon: '#5462d5',
        dark: '#4f4648',
        fairy: '#ffb1ff',
      },
    },
  },
  safelist: [
    'bg-normal',
    'bg-fighting',
    'bg-flying',
    'bg-poison',
    'bg-ground',
    'bg-rock',
    'bg-bug',
    'bg-ghost',
    'bg-steel',
    'bg-fire',
    'bg-water',
    'bg-grass',
    'bg-electric',
    'bg-psychic',
    'bg-ice',
    'bg-dragon',
    'bg-dark',
    'bg-fairy',
  ],
  plugins: [require('daisyui')],
}
export default config
